baseURL = "https://prabowo02.github.io/"
languageCode = "en-us"
title = "Notes"
theme = "slick"
disqusShortname = "prabowo-djonatan"
googleAnalytics = "G-QLDJM2BXDY"

[params]
    showFullContent = false
    showMetaDates = true
    dateFmt = "Mon, 02 Jan 2006 15:04:05 -0700"

[menu]
    [[menu.main]]
        identifier = "post"
        name = "Posts"
        title = "All posts"
        url = "/posts/"
        weight = 1

[markup.goldmark.renderer]
    unsafe = true
