baseURL = "https://prabowo02.github.io/"
languageCode = "en-us"
title = "Notes"
theme = "slick"
disqusShortname = "prabowo-djonatan"
googleAnalytics = "UA-153624663-1"

[params]
    showFullContent = false
    showMetaDates = true

[menu]
    [[menu.main]]
        identifier = "post"
        name = "Posts"
        title = "All posts"
        url = "/posts/"
        weight = 1

[markup.goldmark.renderer]
    unsafe = true
