baseURL = "https://prabowo02.github.io/"
languageCode = "en-us"
title = "Notes"
theme = "slick"

[menu]
    [[menu.main]]
        identifier = "post"
        name = "Posts"
        title = "All posts"
        url = "/posts/"
        weight = 1
